name: Static analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          #- php-version: "8.0"
          - php-version: "8.1"

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Setup PHP
        id: setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: none

      - uses: "ramsey/composer-install@v2"
        with:
          composer-options: "--prefer-dist --no-progress"

      - run: vendor/bin/phpstan
